### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by t1101675** [facebookresearch/task_bench#4]
Interesting work!
I encountered two bugs when I tried to run the code.

1. The `requirements.txt` is missing.
2. It seems that the `TaskBenchData.tar.gz` file is corrupted. I got `gzip: stdin: unexpected end of file` when I ran `tar -xzvf TaskBenchData.tar.gz`.

Could you please help fix them?

**Comment by janedwivedi** [comment]
Thank you for the bug report! 
1. We have added the requirements.txt file.
2. We have updated the instructions for downloading. Please run:
```
wget dl.fbaipublicfiles.com/task_bench/taskbench500.tar.gz
tar -xzvf taskbench500.tar.gz
```
